version: "3.9"

networks:
  ufood-network:
    driver: bridge

services:
  ufood-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - ufood-network

  ufood-api:
    image: ufood-api
    environment:
      DB_HOST: ufood-mysql
    ports:
      - "8080:8080"
    networks:
      - ufood-network
    depends_on:
      - ufood-mysql